default_platform(:ios)

platform :ios do
  
  lane :register_app do
    produce(
    username: "bschick1@mac.com",
    app_identifier: "com.razeware.chew",
    app_name: "Chew Chew Train",
    team_name: "Brian Schick",
    itc_team_name: "Brian Schick"
    )
  end
  
  lane :get_dev_certs do
    cert(development: true)
    sigh(development: true)
  end
  
  desc "Re-obtain match code-signing credentials after switching to a Beginning or Ending project folder"
  lane :bootstrap_code_signing do
    sync_device_info
    match(type: "development")
    match(type: "adhoc")
    match(type: "appstore")
  end
  
  desc "Update iOS UDID's on the Developer Portal"
  lane :sync_device_info do
    register_devices(
    devices_file: "fastlane/Devicefile"
    )
  end
  
  desc "Sync team Development assets"
  lane :sync_all_development do
    sync_device_info
    match(type: "development")
  end
  
end
