# Uncomment the lines below you want to change by removing the # in the beginning

devices([
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone Xs",
  "iPhone Xs Max"
])

languages([
  "en-US",
  "de-DE",
])

scheme("Fastlane Snapshots")
skip_open_summary true